language: cpp

compiler:
  -g++

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq g++-4.9
  - export CXX="g++-4.9"
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-4.9 90
  - sudo apt-get -qq install valgrind
  - sudo apt-get install -y lcov
  - gem install coveralls-lcov

before script:
  - lcov --directory .. --zerocounters

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - valgrind --error-exitcode=42 --leak-check=full --trace-children=yes ./unit_tests

after_success:
  - lcov --directory ./CMakeFiles/unit_tests.dir --capture --output-file coverage.info
  - lcov --remove coverage.info 'tests/*' '/external/*' '/usr/*' --output-file coverage.info
  - lcov --list coverage.info
  - coveralls-lcov coverage.info

notifications:
  email: false
