language: cpp

compiler:
  -g++

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - pip install --user cpp-coveralls

install:
  - sudo apt-get install -qq g++-4.9
  - export CXX="g++-4.9"
  - sudo apt-get -qq install valgrind

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - valgrind --error-exitcode=42 --leak-check=full --trace-children=yes ./unit_tests

after_success:
  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

notifications:
  email: false